# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ql59Jvck2A0N_7g7ewSUPAfhzb3ZLioM
"""

from fastapi import FastAPI
import joblib
import pandas as pd

app = FastAPI(title="Bank Marketing Prediction API")

# Load trained pipeline
model = joblib.load("bank_marketing_model.pkl")

@app.get("/")
def home():
    return {"message": "Bank Marketing Model API is running"}

@app.post("/predict")
def predict(data: dict):
    df = pd.DataFrame([data])
    prediction = model.predict(df)
    return {"prediction": int(prediction[0])}
